# SPDX-FileCopyrightText: 2026 SyoBoN <syobon@syobon.net>
#
# SPDX-License-Identifier: MIT-0

image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
secrets:
  - d34c3fc6-9517-445b-aa79-014ea24dc8a1
tasks:
  - build: |
      cd znes
      nix develop '#build' -c zig build wasm -Doptimize=ReleaseSmall
      nix develop '#build' -c minify -i -r --html-keep-end-tags zig-out/web
  - publish: |
      cd znes
      cp ~/.env.cloudflare .env
      nix develop '#publish' -c wrangler deploy
